services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT:-8081}:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://ajimemo:password@db:5432/ajimemo}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - CACHE_TTL_DEFAULT=${CACHE_TTL_DEFAULT:-86400}
      - RATE_LIMIT_FREE_TIER=${RATE_LIMIT_FREE_TIER:-5}
      - RATE_LIMIT_PREMIUM_TIER=${RATE_LIMIT_PREMIUM_TIER:-1000}
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ajimemo-network

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ajimemo}
      - POSTGRES_USER=${POSTGRES_USER:-ajimemo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/database-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - ajimemo-network

  redis:
    image: redis:8-alpine
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ajimemo-network

volumes:
  postgres_data:
  redis_data:

networks:
  ajimemo-network:
    driver: bridge
